name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código-fonte
      - name: Checkout code
        uses: actions/checkout@v3

      # Login no GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Configurar Buildx com o driver correto
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      # Debug para verificar se o arquivo foi copiado
      - name: Debug file copy
        run: ls -la src/dashboard/
      - name: Debug file copy
        run: ls -la src/dashboard/public

      # Buildar e enviar a imagem Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64  # Adicionado suporte multiplataforma
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:cache
          cache-to: type=inline
